resolver: lts-14.27

packages:
- .

extra-deps:
- lens-4.19.2
- fused-effects-1.1.0.0
- fused-effects-th-0.1.0.2
- fused-effects-lens-1.2.0.1
- readline-1.0.3.0
- extra-1.7.9
- multi-containers-0.1.1

ghc-options:
  "$locals": -Wall -Wno-missing-signatures -Wmissing-exported-signatures -Wno-name-shadowing
